salesforceproject/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Updated_By_Contact__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Updated By Contact</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

salesforceproject/src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Is_Synced__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Is Synced</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

salesforceproject/src/classes/CustomIterable.cls
/**
 * Created by metro on 13.09.2020.
 */

global class CustomIterable implements Iterator<Contact>{

    List<Contact> contactsList {get; set;}
    Integer i {get; set;}

    public CustomIterable(){
        contactsList =  [SELECT Name, Account.Updated_By_Contact__c,
                Account.BillingCountry,
                Account.BillingCity,
                Account.BillingGeocodeAccuracy,
                Account.BillingPostalCode,
                Account.BillingState,
                Account.BillingStreet FROM Contact WHERE Is_Synced__c = FALSE];
        i = 0;
    }

    global boolean hasNext(){
        return (i < contactsList.size());
    }

    global Contact next(){
        if(i == 8) {
            return null;
        }
        i++;
        return contactsList[i-1];
    }
}