salesforceproject/src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Updated_By_Contact__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Updated By Contact</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

salesforceproject/src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Is_Synced__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Is Synced</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

salesforceproject/src/classes/CheduledApexClassTask.cls
/**
 * Created by metro on 13.09.2020.
 */

global class CheduledApexClassTask implements Schedulable {

    private String query = 'Use query\n' +
            '        SELECT Name, Account.Updated_By_Contact__c,\n' +
            '        Account.BillingCountry,\n' +
            '        Account.BillingCity,\n' +
            '        Account.BillingGeocodeAccuracy,\n' +
            '        Account.BillingPostalCode,\n' +
            '        Account.BillingState,\n' +
            '        Account.BillingStreet FROM Contact WHERE Is_Synced__c = FALSE';
//    private String startTime = '0 30 0 * * ?';

    global void execute(SchedulableContext sc) {
        BatchApexClassTask b = new BatchApexClassTask(query);
        BatchApexClassIterableTask b2 = new BatchApexClassIterableTask();
        database.executebatch(b, 100);
        database.executebatch(b2, 100);
    }
}